<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.winter</groupId>
        <artifactId>winter-cloud</artifactId>
        <version>3.6.7</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>winter-cloud-common-log</module>
        <module>winter-cloud-common-core</module>
        <module>winter-cloud-common-redis</module>
        <module>winter-cloud-common-seata</module>
        <module>winter-cloud-common-swagger</module>
        <module>winter-cloud-common-security</module>
        <module>winter-cloud-common-sensitive</module>
        <module>winter-cloud-common-datascope</module>
        <module>winter-cloud-common-datasource</module>
    </modules>

    <artifactId>winter-cloud-common</artifactId>
    <packaging>pom</packaging>

    <description>
        winter-cloud-common通用模块
    </description>

</project>
